// <auto-generated />
using System;
using Almocherifado.InfraEstrutura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Almocherifado.InfraEstrutura.Migrations
{
    [DbContext(typeof(AlmocherifadoContext))]
    [Migration("20210130114817_seed3")]
    partial class seed3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Almocherifado.core.AgregateRoots.EmprestimoNm.Emprestimo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Entrega")
                        .HasColumnType("TEXT");

                    b.Property<string>("FuncionarioCPF")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Obra")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TermoResponsabilidade")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FuncionarioCPF");

                    b.ToTable("Emprestimos");
                });

            modelBuilder.Entity("Almocherifado.core.AgregateRoots.FerramentaNm.Ferramenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCompra")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Marca")
                        .HasColumnType("TEXT");

                    b.Property<string>("Modelo")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeAbreviado")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ferramentas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataCompra = new DateTime(2021, 11, 27, 2, 2, 54, 463, DateTimeKind.Unspecified).AddTicks(2951),
                            Descricao = "descricao88f7951c-2753-4c6a-8327-be7b449deadd",
                            FotoUrl = "132564796661945613.jpg",
                            Marca = "marca70a48d88-0262-4b42-9b40-a009690d1a38",
                            Modelo = "modelo26ee9345-865c-4343-b998-7dfc5bdf6791",
                            NomeAbreviado = "nomeAbreviadob69b60c1-680e-4341-b64b-e13777842942"
                        },
                        new
                        {
                            Id = 2,
                            DataCompra = new DateTime(2019, 12, 21, 10, 33, 46, 20, DateTimeKind.Unspecified).AddTicks(3497),
                            Descricao = "descricaob2ed89d5-2add-48a3-9eb5-9f815a831dd7",
                            FotoUrl = "132564796661945613.jpg",
                            Marca = "marca41f06589-5626-4934-8063-29e096191c30",
                            Modelo = "modelof74530af-596f-4d42-a123-181d102c2288",
                            NomeAbreviado = "nomeAbreviadoba2a99af-1436-4749-87c5-3a43f6648227"
                        },
                        new
                        {
                            Id = 3,
                            DataCompra = new DateTime(2021, 5, 17, 6, 36, 40, 861, DateTimeKind.Unspecified).AddTicks(515),
                            Descricao = "descricao1a5fb676-8db7-4e0b-94e6-b5e15a001558",
                            FotoUrl = "132564796661945613.jpg",
                            Marca = "marcacf920995-9388-40c8-aeea-2bd33df2757a",
                            Modelo = "modelo65bf8413-88a5-40b8-b77d-41dddfb96abc",
                            NomeAbreviado = "nomeAbreviado9e8aacc1-9d6d-4de2-b3ad-57db96296fc6"
                        },
                        new
                        {
                            Id = 4,
                            DataCompra = new DateTime(2022, 6, 9, 2, 36, 32, 198, DateTimeKind.Unspecified).AddTicks(2619),
                            Descricao = "descricao90b4b5ee-f4bc-4e00-a1af-0f9dd79aaf0e",
                            FotoUrl = "132564796661945613.jpg",
                            Marca = "marcacbdb1e39-f686-4520-b9bf-4916b072ebe6",
                            Modelo = "modeloe150daec-6ab8-4849-9422-e9bec19127cd",
                            NomeAbreviado = "nomeAbreviado860743be-3371-4b50-9af9-56ef9ffb4ef0"
                        },
                        new
                        {
                            Id = 5,
                            DataCompra = new DateTime(2020, 4, 12, 5, 41, 0, 501, DateTimeKind.Unspecified).AddTicks(1818),
                            Descricao = "descricao2fab6094-5ce5-40e0-8422-c06e4b1b0b5f",
                            FotoUrl = "132564796661945613.jpg",
                            Marca = "marcafd247573-ffa5-4a1a-8c1e-a854f853d3e2",
                            Modelo = "modelo065add14-2b9d-4015-9020-4a83b32a9272",
                            NomeAbreviado = "nomeAbreviado05abdb90-c952-4f56-a1ba-a137cb9cda1f"
                        },
                        new
                        {
                            Id = 6,
                            DataCompra = new DateTime(2021, 3, 7, 9, 42, 8, 59, DateTimeKind.Unspecified).AddTicks(3615),
                            Descricao = "descricaoeda5c206-ec2e-4dc3-99cc-5344aae9d41a",
                            FotoUrl = "132564796661945613.jpg",
                            Marca = "marca8640754c-5e6f-4dc9-8747-2ac67463595e",
                            Modelo = "modelo774bbfdf-4eac-4c6b-ab1b-7cedfdb7cb48",
                            NomeAbreviado = "nomeAbreviado4a3741f4-7ce2-487b-9c44-5ff7de2121de"
                        },
                        new
                        {
                            Id = 7,
                            DataCompra = new DateTime(2021, 5, 14, 2, 30, 34, 972, DateTimeKind.Unspecified).AddTicks(2535),
                            Descricao = "descricaocb3bfdde-d127-4020-bf0b-00a20551913d",
                            FotoUrl = "132564796661945613.jpg",
                            Marca = "marca945b984e-6773-4e6c-bb32-75ad42abcb82",
                            Modelo = "modelo43fe255d-85b0-46b4-bfd9-71a3c27067b6",
                            NomeAbreviado = "nomeAbreviadoabab0569-a98d-4dd5-95d9-6ab341d586d3"
                        },
                        new
                        {
                            Id = 8,
                            DataCompra = new DateTime(2022, 8, 3, 19, 52, 53, 112, DateTimeKind.Unspecified).AddTicks(9932),
                            Descricao = "descricao09e97732-424a-4d9d-8589-3cfcfb46b05d",
                            FotoUrl = "132564796661945613.jpg",
                            Marca = "marca40bcc05d-2596-438a-bbc2-742bc4945ded",
                            Modelo = "modelo3e560fa3-2c22-45b8-89dd-ce1f12b14d65",
                            NomeAbreviado = "nomeAbreviado2e5cd56b-c203-49f6-b857-c69984a49183"
                        },
                        new
                        {
                            Id = 9,
                            DataCompra = new DateTime(2022, 11, 17, 15, 51, 15, 104, DateTimeKind.Unspecified).AddTicks(2488),
                            Descricao = "descricaoa2f441d8-90ff-4fe6-897a-245219658d9e",
                            FotoUrl = "132564796661945613.jpg",
                            Marca = "marcaa3d95896-7677-4cae-b988-40fb0b07ef1c",
                            Modelo = "modelo1532148f-0d6d-4ed6-8a9d-060dbc3f9bf2",
                            NomeAbreviado = "nomeAbreviado735767b1-7198-4676-a1bd-55512616d414"
                        },
                        new
                        {
                            Id = 10,
                            DataCompra = new DateTime(2020, 1, 29, 3, 5, 17, 26, DateTimeKind.Unspecified).AddTicks(7653),
                            Descricao = "descricao334fcb08-d934-42d4-8674-a62650f32890",
                            FotoUrl = "132564796661945613.jpg",
                            Marca = "marcae804c275-b8bc-4231-a71b-e4efa7d5b43c",
                            Modelo = "modelodf37cc2f-2135-4254-9f9f-3f2e6d6421e3",
                            NomeAbreviado = "nomeAbreviado646cce8e-cc7c-4497-a8f8-9cea288d8311"
                        },
                        new
                        {
                            Id = 11,
                            DataCompra = new DateTime(2019, 5, 9, 9, 55, 9, 558, DateTimeKind.Unspecified).AddTicks(3946),
                            Descricao = "descricaoa943cc2c-257f-4432-89c3-86d5474c6e18",
                            FotoUrl = "132564796661945613.jpg",
                            Marca = "marca1c84826d-a7bb-4765-b5ee-00c052c04753",
                            Modelo = "modeloac12e41c-d584-417a-8ff3-2f8533db9017",
                            NomeAbreviado = "nomeAbreviadod05e9157-dbdb-4bec-a74d-ba84355138a6"
                        },
                        new
                        {
                            Id = 12,
                            DataCompra = new DateTime(2019, 7, 31, 18, 35, 18, 583, DateTimeKind.Unspecified).AddTicks(608),
                            Descricao = "descricaode1599e5-9bec-482e-9cfb-98418aaff1b8",
                            FotoUrl = "132564796661945613.jpg",
                            Marca = "marcaf73470e7-0590-4c73-a17f-ac4442d59f69",
                            Modelo = "modelo31616881-b1ff-44b3-84e5-25632242e46e",
                            NomeAbreviado = "nomeAbreviadoa59c87b8-4598-4767-99ea-db5e72359013"
                        },
                        new
                        {
                            Id = 13,
                            DataCompra = new DateTime(2020, 5, 15, 19, 42, 11, 660, DateTimeKind.Unspecified).AddTicks(4591),
                            Descricao = "descricao4d82baca-19be-4bf7-b6c6-de3f1ac0ceca",
                            FotoUrl = "132564796661945613.jpg",
                            Marca = "marca68b04308-69d3-4582-9851-9e4e6aa047fb",
                            Modelo = "modelo5813f16a-d816-4a4d-8d7b-c83b9d128131",
                            NomeAbreviado = "nomeAbreviadofa4f39dc-b8cb-4cd2-a1e6-095ba8df0e7d"
                        },
                        new
                        {
                            Id = 14,
                            DataCompra = new DateTime(2020, 11, 2, 13, 1, 55, 982, DateTimeKind.Unspecified).AddTicks(2189),
                            Descricao = "descricao82802a50-19fa-45dd-a593-42556c0780c6",
                            FotoUrl = "132564796661945613.jpg",
                            Marca = "marcaa1066a07-bca2-4488-ae79-9feb25436821",
                            Modelo = "modelo84f425eb-392d-4944-b39a-ec6852d54912",
                            NomeAbreviado = "nomeAbreviado5012a6f7-4156-41f7-8926-c64b89257bce"
                        },
                        new
                        {
                            Id = 15,
                            DataCompra = new DateTime(2019, 10, 11, 20, 40, 34, 36, DateTimeKind.Unspecified).AddTicks(5440),
                            Descricao = "descricaod61e9398-cfb0-41a5-ade4-d777b3bf7a47",
                            FotoUrl = "132564796661945613.jpg",
                            Marca = "marca24419dc3-5a20-4a3f-8b7c-3c9f436df7e8",
                            Modelo = "modelo32abc23c-a7af-4e70-ac4a-8e95997de398",
                            NomeAbreviado = "nomeAbreviado8e88ec11-541b-42ca-9896-eb0dfe17c08e"
                        },
                        new
                        {
                            Id = 16,
                            DataCompra = new DateTime(2020, 3, 30, 0, 58, 17, 331, DateTimeKind.Unspecified).AddTicks(3215),
                            Descricao = "descricaoc05d5b2d-935e-47f9-90bd-fe7b31032833",
                            FotoUrl = "132564796661945613.jpg",
                            Marca = "marca3e9bae24-fbd4-442d-8ba2-e3a4f8bbd6e0",
                            Modelo = "modelo730cfc5e-9623-4ef2-a088-c5b525b4d3fc",
                            NomeAbreviado = "nomeAbreviado5dd18536-11bf-43ec-a27d-7f5660a4686f"
                        },
                        new
                        {
                            Id = 17,
                            DataCompra = new DateTime(2019, 3, 23, 7, 45, 59, 424, DateTimeKind.Unspecified).AddTicks(8568),
                            Descricao = "descricao110b291b-17e7-4bdc-8ac9-a650f3384a36",
                            FotoUrl = "132564796661945613.jpg",
                            Marca = "marca35d0755b-945c-49c7-a562-615cdf085c5c",
                            Modelo = "modelo439a62b4-be9d-4cae-bf30-36465b869877",
                            NomeAbreviado = "nomeAbreviado7e00b761-b71e-4070-9548-14ec08995744"
                        },
                        new
                        {
                            Id = 18,
                            DataCompra = new DateTime(2023, 1, 18, 20, 3, 33, 846, DateTimeKind.Unspecified).AddTicks(6220),
                            Descricao = "descricao2eba473d-9a3b-4891-ba38-05074918ad02",
                            FotoUrl = "132564796661945613.jpg",
                            Marca = "marca96aa62c0-9231-47f0-95be-65f3b740ae02",
                            Modelo = "modelo29a29088-87b3-47a0-bc31-82a9b0a7e1a1",
                            NomeAbreviado = "nomeAbreviado4d270990-eb9e-4c1b-ac4e-11395296e163"
                        },
                        new
                        {
                            Id = 19,
                            DataCompra = new DateTime(2021, 9, 21, 1, 58, 12, 352, DateTimeKind.Unspecified).AddTicks(5489),
                            Descricao = "descricao30cca452-8867-4903-8c37-9fc8c9992001",
                            FotoUrl = "132564796661945613.jpg",
                            Marca = "marca5bc85d79-2766-4c0b-a986-6d0dfd50bd59",
                            Modelo = "modelo81b18747-13d4-4bda-be7c-353e932d4a8e",
                            NomeAbreviado = "nomeAbreviadofa5e64e4-50db-437c-87f5-b8118751355d"
                        },
                        new
                        {
                            Id = 20,
                            DataCompra = new DateTime(2020, 12, 24, 14, 0, 32, 36, DateTimeKind.Unspecified).AddTicks(390),
                            Descricao = "descricao25fdd981-72b7-4869-a48c-35cec1b8f50e",
                            FotoUrl = "132564796661945613.jpg",
                            Marca = "marca82da798f-fea7-40b5-83bf-30e1861742cd",
                            Modelo = "modeloe16a001f-c83e-4029-bc53-1cb25fc82eb0",
                            NomeAbreviado = "nomeAbreviado965063f1-368a-43f4-98cd-1d4080ae2506"
                        },
                        new
                        {
                            Id = 21,
                            DataCompra = new DateTime(2022, 1, 24, 6, 23, 15, 584, DateTimeKind.Unspecified).AddTicks(9343),
                            Descricao = "descricaodcf74512-abbd-4e7e-abdf-e54e40000079",
                            FotoUrl = "132564796661945613.jpg",
                            Marca = "marcaac06bb0b-4142-436d-985d-5b42aea87913",
                            Modelo = "modelo50870927-9cf6-4152-b7ba-a6d4f59bc716",
                            NomeAbreviado = "nomeAbreviadof5ebd79e-fca7-4f95-8d3c-24eeda3f0d37"
                        },
                        new
                        {
                            Id = 22,
                            DataCompra = new DateTime(2022, 8, 18, 2, 19, 46, 680, DateTimeKind.Unspecified).AddTicks(1190),
                            Descricao = "descricao298e5b3c-7477-4902-859c-d7ab29912451",
                            FotoUrl = "132564796661945613.jpg",
                            Marca = "marca56defbaa-309f-47c4-8207-7fa61e8b2bf8",
                            Modelo = "modelod4aaf206-051f-476a-a3fe-75ec072013e6",
                            NomeAbreviado = "nomeAbreviadoe07c82e5-973b-47aa-997b-9d7fa562809e"
                        },
                        new
                        {
                            Id = 23,
                            DataCompra = new DateTime(2021, 5, 7, 14, 1, 57, 717, DateTimeKind.Unspecified).AddTicks(8327),
                            Descricao = "descricao19c44d5c-73c6-4d4f-957e-7eca59668402",
                            FotoUrl = "132564796661945613.jpg",
                            Marca = "marcae510ca0a-9e35-4b5e-94f7-d6bc3731f9ee",
                            Modelo = "modelo3273ea96-0586-49de-aa65-2e23dfbb6306",
                            NomeAbreviado = "nomeAbreviado037974ba-fe85-43a6-9258-9656cb1401d3"
                        },
                        new
                        {
                            Id = 24,
                            DataCompra = new DateTime(2020, 6, 4, 2, 48, 34, 672, DateTimeKind.Unspecified).AddTicks(5785),
                            Descricao = "descricao209e184a-cd0a-454a-9a12-6a987c9cafdf",
                            FotoUrl = "132564796661945613.jpg",
                            Marca = "marca7079f5cc-e039-404f-8d8a-10c37f6977d0",
                            Modelo = "modelo5e061026-27e3-4de7-acf1-057b5447c790",
                            NomeAbreviado = "nomeAbreviado7c73514e-4f93-437a-b222-1d2c531030b2"
                        },
                        new
                        {
                            Id = 25,
                            DataCompra = new DateTime(2020, 8, 1, 11, 28, 14, 981, DateTimeKind.Unspecified).AddTicks(4972),
                            Descricao = "descricaob3e2d35d-3b9e-4bb1-8d10-13a13e7328d1",
                            FotoUrl = "132564796661945613.jpg",
                            Marca = "marcac0b17813-11f8-4081-ba28-52c37b91bf19",
                            Modelo = "modelo8bd4a8b9-c6c1-45be-8650-3210db2d63b0",
                            NomeAbreviado = "nomeAbreviado2d30ebc1-293d-4481-aeee-a117fedec736"
                        },
                        new
                        {
                            Id = 26,
                            DataCompra = new DateTime(2022, 9, 14, 21, 21, 45, 440, DateTimeKind.Unspecified).AddTicks(3612),
                            Descricao = "descricao7758b43c-8d94-4886-9218-71bbbf4fae4e",
                            FotoUrl = "132564796661945613.jpg",
                            Marca = "marcace14aaed-6a8f-4e4f-abaa-9faf8aa6ffff",
                            Modelo = "modelo7546f024-bc98-4169-b624-5d878ec2d1f6",
                            NomeAbreviado = "nomeAbreviadod8906668-a5b6-4a42-b4b5-ad2459a558a9"
                        },
                        new
                        {
                            Id = 27,
                            DataCompra = new DateTime(2022, 1, 19, 4, 5, 49, 372, DateTimeKind.Unspecified).AddTicks(5488),
                            Descricao = "descricao98ed01ff-ec64-4b67-8430-8d70af96c294",
                            FotoUrl = "132564796661945613.jpg",
                            Marca = "marca7d86d267-8cef-4527-b986-59cd6dfcffb1",
                            Modelo = "modelo9615cf08-76bf-4554-8254-ff11705c20de",
                            NomeAbreviado = "nomeAbreviado0597c58f-5782-4b9b-a534-0ef2d8e73ea9"
                        },
                        new
                        {
                            Id = 28,
                            DataCompra = new DateTime(2020, 9, 20, 11, 55, 48, 147, DateTimeKind.Unspecified).AddTicks(5981),
                            Descricao = "descricao51888833-61f2-4c68-977f-d74e373c75f9",
                            FotoUrl = "132564796661945613.jpg",
                            Marca = "marcabf266a2e-3200-4733-ba10-140c182f02a4",
                            Modelo = "modelo190d2323-1be5-4d64-b75f-1c781f827090",
                            NomeAbreviado = "nomeAbreviadoa9ff7016-0055-4adc-ad9d-88e4d5d96bf5"
                        },
                        new
                        {
                            Id = 29,
                            DataCompra = new DateTime(2021, 8, 24, 2, 5, 34, 870, DateTimeKind.Unspecified).AddTicks(567),
                            Descricao = "descricao346ae396-ab37-45eb-9bef-9566e6cfef1c",
                            FotoUrl = "132564796661945613.jpg",
                            Marca = "marca510fed18-7b98-44ab-8254-1e3cb5b40db1",
                            Modelo = "modeloee6a87b9-848d-43d6-a88a-ac7b8eacc7d1",
                            NomeAbreviado = "nomeAbreviado14d77eac-e902-43d6-8541-8be1d179e912"
                        },
                        new
                        {
                            Id = 30,
                            DataCompra = new DateTime(2019, 4, 13, 8, 28, 21, 142, DateTimeKind.Unspecified).AddTicks(9823),
                            Descricao = "descricaoc27356b9-4160-4828-a89c-0a95c6baa73d",
                            FotoUrl = "132564796661945613.jpg",
                            Marca = "marcad9016644-a7a7-455f-965c-a4b78e84076c",
                            Modelo = "modelo8aa31758-18a8-4fca-9fb0-c1121462509a",
                            NomeAbreviado = "nomeAbreviado794328a2-7635-4cd4-969e-6a2feed4e9eb"
                        },
                        new
                        {
                            Id = 31,
                            DataCompra = new DateTime(2019, 9, 14, 16, 48, 24, 6, DateTimeKind.Unspecified).AddTicks(7631),
                            Descricao = "descricao7f08700f-ef4e-4719-8b40-0886ce45b0ce",
                            FotoUrl = "132564796661945613.jpg",
                            Marca = "marcaf1eacbfd-d399-4a09-9502-3aadf375cf09",
                            Modelo = "modelo0f64b843-1cfa-4999-8c2d-01556957b49b",
                            NomeAbreviado = "nomeAbreviado64e614dd-7a5b-49eb-bd58-3e5e558fe7f2"
                        },
                        new
                        {
                            Id = 32,
                            DataCompra = new DateTime(2020, 8, 17, 23, 28, 36, 420, DateTimeKind.Unspecified).AddTicks(7910),
                            Descricao = "descricaoff3823de-84cd-4b92-bc42-83ab9a058054",
                            FotoUrl = "132564796661945613.jpg",
                            Marca = "marcaf163e81b-1534-4ab2-927c-9e95388dd24f",
                            Modelo = "modeloe6a9b56a-32f2-4c47-8b7f-f725a7319f93",
                            NomeAbreviado = "nomeAbreviadod5f93fe0-d441-416f-ae0e-3ca43166d7bb"
                        },
                        new
                        {
                            Id = 33,
                            DataCompra = new DateTime(2021, 3, 25, 11, 37, 50, 735, DateTimeKind.Unspecified).AddTicks(6472),
                            Descricao = "descricao0637dd36-28ca-49a7-8c3f-3cc44121f5e6",
                            FotoUrl = "132564796661945613.jpg",
                            Marca = "marca90edfb30-0e90-40c2-80c6-8c0b6a7bf167",
                            Modelo = "modeloe3a41545-193f-44d5-970c-fd19e5f6b059",
                            NomeAbreviado = "nomeAbreviado0e8338e8-c052-46ec-9b3b-10d128e36ce1"
                        },
                        new
                        {
                            Id = 34,
                            DataCompra = new DateTime(2019, 10, 3, 18, 24, 44, 431, DateTimeKind.Unspecified).AddTicks(9722),
                            Descricao = "descricao24f48faf-83ff-416f-9248-25bdfecbb6a6",
                            FotoUrl = "132564796661945613.jpg",
                            Marca = "marca20a75329-0c06-456e-a14f-8f7c064e5247",
                            Modelo = "modelo2eb05e1d-67e1-4a58-b711-a9b30187c254",
                            NomeAbreviado = "nomeAbreviado114b4fae-e908-4db3-99aa-7bfb3757bd1d"
                        },
                        new
                        {
                            Id = 35,
                            DataCompra = new DateTime(2020, 4, 29, 13, 9, 50, 736, DateTimeKind.Unspecified).AddTicks(2903),
                            Descricao = "descricaoc6bb2c62-8f56-4220-9b96-1cbe256d268d",
                            FotoUrl = "132564796661945613.jpg",
                            Marca = "marca3b32a3aa-0277-4742-95e7-36dc907bf939",
                            Modelo = "modelo83efe00b-356b-4b24-a200-6011ef6c4cf5",
                            NomeAbreviado = "nomeAbreviado3ce0706c-455a-4cda-bf5a-2d19ed5f92d2"
                        },
                        new
                        {
                            Id = 36,
                            DataCompra = new DateTime(2022, 2, 11, 18, 45, 6, 120, DateTimeKind.Unspecified).AddTicks(7938),
                            Descricao = "descricao869e05b4-726e-4a08-b9ce-7aeeb4cdbbfd",
                            FotoUrl = "132564796661945613.jpg",
                            Marca = "marcae06fe824-5696-4c49-a252-459f51283353",
                            Modelo = "modelo2b4e89d2-6990-45cd-9818-5f354f4ab166",
                            NomeAbreviado = "nomeAbreviadofd337d1c-5760-4948-9f70-1a3f82bc80f9"
                        },
                        new
                        {
                            Id = 37,
                            DataCompra = new DateTime(2019, 3, 4, 12, 36, 20, 255, DateTimeKind.Unspecified).AddTicks(7451),
                            Descricao = "descricao63fb1796-9d24-46e0-9073-cf68e17e37e2",
                            FotoUrl = "132564796661945613.jpg",
                            Marca = "marca47a4dae3-78bc-48db-8ae7-c5bb536abd7a",
                            Modelo = "modelobdf32598-395d-40bf-84bf-e7e25af420e7",
                            NomeAbreviado = "nomeAbreviadoadcd5516-acea-46cb-98bc-84280a94615e"
                        },
                        new
                        {
                            Id = 38,
                            DataCompra = new DateTime(2022, 6, 20, 20, 34, 10, 65, DateTimeKind.Unspecified).AddTicks(6365),
                            Descricao = "descricao170ee8b7-5542-49a1-8dce-7873c8e173f3",
                            FotoUrl = "132564796661945613.jpg",
                            Marca = "marcadd6478fb-0a6d-4b4d-9487-a8c9c016ebc1",
                            Modelo = "modelo5a83759b-9fd4-4c00-a35b-b89f2c00460f",
                            NomeAbreviado = "nomeAbreviadof7c5fb95-9f10-4e8e-bcb9-80372e398271"
                        },
                        new
                        {
                            Id = 39,
                            DataCompra = new DateTime(2021, 6, 5, 13, 28, 28, 489, DateTimeKind.Unspecified).AddTicks(8229),
                            Descricao = "descricao1ba4d36f-130f-4c20-a709-6ddf2672beff",
                            FotoUrl = "132564796661945613.jpg",
                            Marca = "marcae6f6ccf8-5c71-4479-8827-50aea9bbc24f",
                            Modelo = "modelo8db2f9a8-aa55-4197-bc9d-c4a3c47b8e29",
                            NomeAbreviado = "nomeAbreviado0d42ea89-9053-4af1-afab-5e228635d0cf"
                        },
                        new
                        {
                            Id = 40,
                            DataCompra = new DateTime(2020, 9, 22, 15, 18, 5, 516, DateTimeKind.Unspecified).AddTicks(1329),
                            Descricao = "descricao1e169a72-0a1e-4110-99e7-ee27e8cbd59d",
                            FotoUrl = "132564796661945613.jpg",
                            Marca = "marca68ced998-1dc2-4ec7-99f4-227e9287681a",
                            Modelo = "modelo592dd28b-a87e-438c-9dd6-216d0d55623b",
                            NomeAbreviado = "nomeAbreviado61725151-8cc1-43cf-922b-d2c262223dcd"
                        },
                        new
                        {
                            Id = 41,
                            DataCompra = new DateTime(2021, 3, 17, 4, 55, 33, 296, DateTimeKind.Unspecified).AddTicks(1192),
                            Descricao = "descricao6dc243ad-0ab0-4942-a55a-d8b98d0ad9f6",
                            FotoUrl = "132564796661945613.jpg",
                            Marca = "marca8a51cce6-0925-4836-92a8-d7f2ef204894",
                            Modelo = "modelo06e5e4bb-3ed2-4d67-9f52-a1292f2f8daf",
                            NomeAbreviado = "nomeAbreviadoc354add3-21a5-403f-bbfa-aee4b235b228"
                        },
                        new
                        {
                            Id = 42,
                            DataCompra = new DateTime(2019, 3, 22, 6, 55, 15, 237, DateTimeKind.Unspecified).AddTicks(7531),
                            Descricao = "descricaoc408f920-b9d8-4d3f-8d16-fd78645c86fa",
                            FotoUrl = "132564796661945613.jpg",
                            Marca = "marcaa9fe69e9-210d-43eb-bebf-7c0dcb0d9d30",
                            Modelo = "modelo639612ac-4329-4943-a4ec-1112a4100f39",
                            NomeAbreviado = "nomeAbreviado96fa5fcf-4604-4fb9-abab-03a907b11081"
                        },
                        new
                        {
                            Id = 43,
                            DataCompra = new DateTime(2019, 2, 17, 19, 31, 15, 503, DateTimeKind.Unspecified).AddTicks(5468),
                            Descricao = "descricaoa6214fba-c047-41ed-8c3d-a4faf3837e13",
                            FotoUrl = "132564796661945613.jpg",
                            Marca = "marcaec832b63-687e-4cca-97c2-64ac9e1c4be7",
                            Modelo = "modelo22005862-73b2-4847-851c-bc6f8343d5da",
                            NomeAbreviado = "nomeAbreviado7eb6e7d2-931f-47fb-b58a-e0494761a858"
                        },
                        new
                        {
                            Id = 44,
                            DataCompra = new DateTime(2020, 8, 17, 22, 17, 6, 868, DateTimeKind.Unspecified).AddTicks(5444),
                            Descricao = "descricao929b16e7-59a3-4da9-9582-0800be269986",
                            FotoUrl = "132564796661945613.jpg",
                            Marca = "marcae4948726-e674-4ccd-9862-fa695c52657c",
                            Modelo = "modeloe7ab64a8-95cb-4ae4-bda9-5aac091eecd5",
                            NomeAbreviado = "nomeAbreviado032d70ce-70f8-4e65-b0aa-23671b27989c"
                        },
                        new
                        {
                            Id = 45,
                            DataCompra = new DateTime(2020, 9, 29, 10, 55, 7, 898, DateTimeKind.Unspecified).AddTicks(6525),
                            Descricao = "descricao7f2ec1de-38e2-40a6-866d-4d807c5d7455",
                            FotoUrl = "132564796661945613.jpg",
                            Marca = "marcae43da19b-d036-456d-8d58-979254338570",
                            Modelo = "modelo7c1d538e-7bc5-4d4b-a914-f1cf80c508cb",
                            NomeAbreviado = "nomeAbreviado0eb7918a-bd28-43aa-b6b5-c74bfb2b0cea"
                        },
                        new
                        {
                            Id = 46,
                            DataCompra = new DateTime(2019, 7, 30, 16, 9, 54, 234, DateTimeKind.Unspecified).AddTicks(7578),
                            Descricao = "descricao986d2188-7e33-41ff-8081-6b7eaf71bea9",
                            FotoUrl = "132564796661945613.jpg",
                            Marca = "marcab4fafcb5-1da7-44f4-ad3f-4bea8e5f07c0",
                            Modelo = "modelo86da8f96-72dd-468e-a276-2fd77ae823a7",
                            NomeAbreviado = "nomeAbreviadoeb8acb0c-8fae-41f4-8309-b380fee8baab"
                        },
                        new
                        {
                            Id = 47,
                            DataCompra = new DateTime(2020, 9, 7, 4, 0, 31, 131, DateTimeKind.Unspecified).AddTicks(6508),
                            Descricao = "descricao13e16046-094c-4712-8beb-bd817555a9ed",
                            FotoUrl = "132564796661945613.jpg",
                            Marca = "marcac23ef2d4-9bad-4e8c-8aaa-7ba5be500e12",
                            Modelo = "modelodbf0b477-c607-450f-bfda-04cfe98cdf1c",
                            NomeAbreviado = "nomeAbreviado79ee4562-3466-4b5d-b208-b60eaaa1b73a"
                        },
                        new
                        {
                            Id = 48,
                            DataCompra = new DateTime(2020, 3, 20, 15, 51, 30, 276, DateTimeKind.Unspecified).AddTicks(7025),
                            Descricao = "descricao29e1e0d5-4af6-4d99-af40-d16047b00ec5",
                            FotoUrl = "132564796661945613.jpg",
                            Marca = "marca240673f3-fd4f-4c5e-9c96-e4b06abd2a41",
                            Modelo = "modeloa8ee59ec-902e-4b81-9194-57b4d1397136",
                            NomeAbreviado = "nomeAbreviadoa3400439-079f-40f9-9bc4-263acf19edbb"
                        },
                        new
                        {
                            Id = 49,
                            DataCompra = new DateTime(2022, 11, 18, 0, 31, 26, 716, DateTimeKind.Unspecified).AddTicks(8899),
                            Descricao = "descricao6652a1e9-b610-4c98-8aa0-308f7529c081",
                            FotoUrl = "132564796661945613.jpg",
                            Marca = "marca0af7e156-a75a-4ef2-a993-ea4330f7f5f6",
                            Modelo = "modelob189fef7-7469-4c79-85dd-3deb840b2d4e",
                            NomeAbreviado = "nomeAbreviado8e4157b4-27f5-4cd3-b76e-48dc6c9474ae"
                        },
                        new
                        {
                            Id = 50,
                            DataCompra = new DateTime(2022, 12, 21, 10, 43, 54, 447, DateTimeKind.Unspecified).AddTicks(8692),
                            Descricao = "descricao65202457-9dfa-40d5-838b-d07b6ba8d905",
                            FotoUrl = "132564796661945613.jpg",
                            Marca = "marcac8a4e062-7cd6-42bf-8154-f29db099ffa2",
                            Modelo = "modelo066941d1-fc91-4605-bf20-baabd443013f",
                            NomeAbreviado = "nomeAbreviado1becf60c-f850-4751-ab0f-05579eb54ac5"
                        });
                });

            modelBuilder.Entity("Almocherifado.core.AgregateRoots.FerramentaNm.FerramentaEmprestada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataDevolucao")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EmprestimoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FerramentaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmprestimoId");

                    b.HasIndex("FerramentaId");

                    b.HasIndex("Id");

                    b.ToTable("FerramentaEmprestada");
                });

            modelBuilder.Entity("Almocherifado.core.AgregateRoots.FuncionarioNm.Funcionario", b =>
                {
                    b.Property<string>("CPF")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("CPF");

                    b.ToTable("Funcionarios");

                    b.HasData(
                        new
                        {
                            CPF = "04408216143",
                            Email = "Kristine.Santos@gmail.com",
                            Nome = "Harriet Carvalho"
                        },
                        new
                        {
                            CPF = "01809901448",
                            Email = "Sherry.Saraiva@gmail.com",
                            Nome = "Lucille Souza"
                        },
                        new
                        {
                            CPF = "47353301198",
                            Email = "Kim5@bol.com.br",
                            Nome = "Howard Pereira"
                        },
                        new
                        {
                            CPF = "89152796973",
                            Email = "Wilma54@gmail.com",
                            Nome = "Hazel Albuquerque"
                        },
                        new
                        {
                            CPF = "79359369004",
                            Email = "Michael_Barros80@gmail.com",
                            Nome = "Lela Souza"
                        },
                        new
                        {
                            CPF = "76726119763",
                            Email = "Ralph.Xavier@hotmail.com",
                            Nome = "Rick Batista"
                        },
                        new
                        {
                            CPF = "78808082300",
                            Email = "Paulette_Martins@yahoo.com",
                            Nome = "Ethel Xavier"
                        },
                        new
                        {
                            CPF = "54631329840",
                            Email = "Brett12@live.com",
                            Nome = "Chester Costa"
                        },
                        new
                        {
                            CPF = "50408658134",
                            Email = "Stuart.Moraes@hotmail.com",
                            Nome = "Taylor Batista"
                        },
                        new
                        {
                            CPF = "05647974309",
                            Email = "Evelyn33@bol.com.br",
                            Nome = "Lydia Oliveira"
                        });
                });

            modelBuilder.Entity("Almocherifado.core.AgregateRoots.EmprestimoNm.Emprestimo", b =>
                {
                    b.HasOne("Almocherifado.core.AgregateRoots.FuncionarioNm.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioCPF")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("Almocherifado.core.AgregateRoots.FerramentaNm.FerramentaEmprestada", b =>
                {
                    b.HasOne("Almocherifado.core.AgregateRoots.EmprestimoNm.Emprestimo", "Emprestimo")
                        .WithMany("FerramentasEmprestas")
                        .HasForeignKey("EmprestimoId");

                    b.HasOne("Almocherifado.core.AgregateRoots.FerramentaNm.Ferramenta", "Ferramenta")
                        .WithMany("HistoricoEmprestimos")
                        .HasForeignKey("FerramentaId");

                    b.Navigation("Emprestimo");

                    b.Navigation("Ferramenta");
                });

            modelBuilder.Entity("Almocherifado.core.AgregateRoots.EmprestimoNm.Emprestimo", b =>
                {
                    b.Navigation("FerramentasEmprestas");
                });

            modelBuilder.Entity("Almocherifado.core.AgregateRoots.FerramentaNm.Ferramenta", b =>
                {
                    b.Navigation("HistoricoEmprestimos");
                });
#pragma warning restore 612, 618
        }
    }
}
