// <auto-generated />
using System;
using Almocherifado.InfraEstrutura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Almocherifado.InfraEstrutura.Migrations
{
    [DbContext(typeof(AlmocherifadoContext))]
    [Migration("20210130111746_seed")]
    partial class seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Almocherifado.core.AgregateRoots.EmprestimoNm.Emprestimo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Entrega")
                        .HasColumnType("TEXT");

                    b.Property<string>("FuncionarioCPF")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Obra")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TermoResponsabilidade")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FuncionarioCPF");

                    b.ToTable("Emprestimos");
                });

            modelBuilder.Entity("Almocherifado.core.AgregateRoots.FerramentaNm.Ferramenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCompra")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Marca")
                        .HasColumnType("TEXT");

                    b.Property<string>("Modelo")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeAbreviado")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ferramentas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataCompra = new DateTime(2020, 4, 4, 12, 52, 14, 168, DateTimeKind.Unspecified).AddTicks(9033),
                            Descricao = "descricao45feac62-2a7f-41f0-b9eb-b2daa4a12858",
                            FotoUrl = "fotoUrle9bc6eed-c93c-4ad3-9c10-ee0b88a18a82",
                            Marca = "marcaf0d9fa73-7817-47c5-813b-b5f34804f14f",
                            Modelo = "modelo826436c0-a101-4bc3-bb4c-571737bd8c3b",
                            NomeAbreviado = "nomeAbreviado322a77b6-89da-4d57-87e6-ea08210c3099"
                        },
                        new
                        {
                            Id = 2,
                            DataCompra = new DateTime(2020, 5, 15, 19, 3, 54, 663, DateTimeKind.Unspecified).AddTicks(5985),
                            Descricao = "descricaof6b2a6d3-3d82-41b3-abe8-250811437262",
                            FotoUrl = "fotoUrl0a71144a-4d52-4ff0-85ab-cd12940fa338",
                            Marca = "marcaea7bb857-90b2-480a-9fea-e190d376d7dc",
                            Modelo = "modelo977c2d39-4aef-42d6-adba-24d8d1905cf1",
                            NomeAbreviado = "nomeAbreviado8b4ffc33-5905-424d-8c52-4f7b8010e186"
                        },
                        new
                        {
                            Id = 3,
                            DataCompra = new DateTime(2021, 10, 16, 17, 41, 50, 748, DateTimeKind.Unspecified).AddTicks(4768),
                            Descricao = "descricaocd91afaf-7520-46ec-8751-c5a69a871532",
                            FotoUrl = "fotoUrlcaa2c1c6-2cca-4e4e-bbf4-1a2e4e633141",
                            Marca = "marcaca74d5f5-fc12-493d-8e42-aaa95becbceb",
                            Modelo = "modelo10135220-cc86-4a6c-9344-515b5fafc9ef",
                            NomeAbreviado = "nomeAbreviadobbd99169-1c7c-485a-ada4-b6eed0bdded7"
                        },
                        new
                        {
                            Id = 4,
                            DataCompra = new DateTime(2020, 7, 3, 20, 31, 48, 633, DateTimeKind.Unspecified).AddTicks(665),
                            Descricao = "descricao72629a67-3e70-441e-9990-3a735ae2c630",
                            FotoUrl = "fotoUrl8ababcac-bd48-4a89-9400-1e6e32315b90",
                            Marca = "marca59006ef2-d1ec-4bc9-bddd-1eb257e95115",
                            Modelo = "modelo81793bae-ab85-4f5d-a26a-a554d5e1cc39",
                            NomeAbreviado = "nomeAbreviado61bd036e-1d57-48e2-a62d-2e76e733a71c"
                        },
                        new
                        {
                            Id = 5,
                            DataCompra = new DateTime(2021, 5, 9, 17, 18, 34, 145, DateTimeKind.Unspecified).AddTicks(9481),
                            Descricao = "descricao5b1cb191-ef5b-4f6d-ac9f-83468f23bcdd",
                            FotoUrl = "fotoUrl2d24705c-1e44-477d-9b4c-af242c169ecc",
                            Marca = "marca445f2355-3356-4ded-8723-2a8e4abb9dcf",
                            Modelo = "modelo9144fa33-681e-4bff-b03c-2e4c69e97af0",
                            NomeAbreviado = "nomeAbreviadoa30f9d8d-0993-4752-8d5e-42b651c417e3"
                        },
                        new
                        {
                            Id = 6,
                            DataCompra = new DateTime(2022, 6, 30, 7, 17, 56, 504, DateTimeKind.Unspecified).AddTicks(4014),
                            Descricao = "descricao1f8eac08-3f8c-48bd-86f8-10fb01b4b37b",
                            FotoUrl = "fotoUrl3c572533-a4a7-4938-92dd-ca0bda7a0b08",
                            Marca = "marcabe486ffb-d8ff-4f90-842d-0de89373055f",
                            Modelo = "modelobd191a47-d104-416d-b45f-4a91bc27dc28",
                            NomeAbreviado = "nomeAbreviadof1403afb-92e5-4350-bfc4-081d618c0206"
                        },
                        new
                        {
                            Id = 7,
                            DataCompra = new DateTime(2020, 3, 4, 15, 59, 2, 771, DateTimeKind.Unspecified).AddTicks(8070),
                            Descricao = "descricaoa9a85ad5-3ca3-4ee0-97af-6e8b59e73884",
                            FotoUrl = "fotoUrl8da1703f-cbbc-4d34-801a-33b22feea1f8",
                            Marca = "marca48fd7512-feae-4ac8-b5be-b31e953ff3aa",
                            Modelo = "modelo2cfbbed2-0b91-4980-bc25-b8cd65d4f33e",
                            NomeAbreviado = "nomeAbreviado8853f950-856b-4b78-85ff-f94d9e8e80e2"
                        },
                        new
                        {
                            Id = 8,
                            DataCompra = new DateTime(2022, 4, 2, 11, 27, 22, 961, DateTimeKind.Unspecified).AddTicks(7140),
                            Descricao = "descricaocffcd5ea-7474-49b9-bf97-b32da0502431",
                            FotoUrl = "fotoUrl6c4d6059-00fe-4f6a-860e-76c04549fef6",
                            Marca = "marca2cf6383f-0a1c-4637-ac3d-62662b2c71a4",
                            Modelo = "modelobc527cd4-ed6b-4359-87e8-3503922f4073",
                            NomeAbreviado = "nomeAbreviado89f6d3ab-ba08-41ed-b806-4cabc5fa1ee5"
                        },
                        new
                        {
                            Id = 9,
                            DataCompra = new DateTime(2022, 7, 1, 22, 59, 0, 289, DateTimeKind.Unspecified).AddTicks(2742),
                            Descricao = "descricaoa5378543-e5c5-465e-b1f3-0713fce2f28e",
                            FotoUrl = "fotoUrl2de4da36-4c91-4226-9b22-93016abf09df",
                            Marca = "marcaeed2adba-9765-4300-8ef2-2f1d0500d6b1",
                            Modelo = "modelo5b70a520-2f4c-41f4-b26e-67b498ef8787",
                            NomeAbreviado = "nomeAbreviado08425798-5b02-40bd-a30a-89aa303d3280"
                        },
                        new
                        {
                            Id = 10,
                            DataCompra = new DateTime(2019, 3, 26, 18, 35, 29, 661, DateTimeKind.Unspecified).AddTicks(8482),
                            Descricao = "descricaof609529e-4344-40bd-9074-d145bf93d441",
                            FotoUrl = "fotoUrlf432d016-3180-4646-9dd7-6de92cff0ba6",
                            Marca = "marca04f940d3-fdca-43bc-ad30-eec3eb7c4357",
                            Modelo = "modelo29588709-9576-4785-8cb6-d70b85545d73",
                            NomeAbreviado = "nomeAbreviadod2ce29f8-36be-41b9-84a3-816607aa8eeb"
                        },
                        new
                        {
                            Id = 11,
                            DataCompra = new DateTime(2021, 10, 2, 2, 8, 6, 26, DateTimeKind.Unspecified).AddTicks(9228),
                            Descricao = "descricaoe127844c-338f-487f-b1c7-b527f142d9fb",
                            FotoUrl = "fotoUrl47bb96ba-c501-452a-b6da-946837973792",
                            Marca = "marcaf4376c5e-2da4-41b7-9dd0-9988ca69549f",
                            Modelo = "modelo4ab83963-cd2b-4226-8406-33c11e999972",
                            NomeAbreviado = "nomeAbreviado4be4a923-c70a-4dc8-85d6-8f9f65e082a9"
                        },
                        new
                        {
                            Id = 12,
                            DataCompra = new DateTime(2022, 2, 26, 3, 27, 45, 540, DateTimeKind.Unspecified).AddTicks(4931),
                            Descricao = "descricaob6db585b-a832-476a-97f7-5aa45385b793",
                            FotoUrl = "fotoUrlae387a8b-804c-4e3f-aedd-4266eea1a8a9",
                            Marca = "marcaebcf6ec4-305f-400d-8de4-43373a1bbe7d",
                            Modelo = "modeloa354d4ae-b24d-45b7-9e6b-3602362d0999",
                            NomeAbreviado = "nomeAbreviado2dd0b7ef-5dd6-479d-98ef-d0acc174493d"
                        },
                        new
                        {
                            Id = 13,
                            DataCompra = new DateTime(2021, 4, 18, 3, 34, 28, 391, DateTimeKind.Unspecified).AddTicks(4169),
                            Descricao = "descricaob9b911ab-769f-4e68-889f-2d4d022a80da",
                            FotoUrl = "fotoUrl5f7ea30b-5fe5-4e23-b436-b019e05a1a6f",
                            Marca = "marcaead127d3-a401-4e4d-9ded-ddbe82abf56f",
                            Modelo = "modelob9a72266-a8d1-49e5-8573-ff1ac92ad65e",
                            NomeAbreviado = "nomeAbreviado9f389947-2d2b-4d6d-8353-6832ba71c930"
                        },
                        new
                        {
                            Id = 14,
                            DataCompra = new DateTime(2019, 3, 22, 19, 35, 39, 40, DateTimeKind.Unspecified).AddTicks(9110),
                            Descricao = "descricao60b329d5-fc7b-4d9f-baff-652346c46526",
                            FotoUrl = "fotoUrl847c7b71-be98-44ba-9eac-ba3a4dcc0645",
                            Marca = "marcaac6d6a42-c7cf-4f9c-bc96-8cd9c3debb16",
                            Modelo = "modelo8e80d34a-4dae-4140-9bca-456827c56bbd",
                            NomeAbreviado = "nomeAbreviado85c8f2d4-8e4b-4537-8fbd-2177579665c7"
                        },
                        new
                        {
                            Id = 15,
                            DataCompra = new DateTime(2021, 6, 2, 23, 51, 28, 476, DateTimeKind.Unspecified).AddTicks(9333),
                            Descricao = "descricaobce6515e-6403-48f9-b10f-32d379e56ca3",
                            FotoUrl = "fotoUrl29782b10-0144-4879-a679-e9680bde5bcb",
                            Marca = "marca04fd2d04-c64c-4b54-9966-ef4a8d01944d",
                            Modelo = "modelo3cf0711d-efa2-4c96-bc7d-ab55852df050",
                            NomeAbreviado = "nomeAbreviadof5db84da-9b7e-48db-b924-1e8347be9f41"
                        },
                        new
                        {
                            Id = 16,
                            DataCompra = new DateTime(2022, 12, 15, 8, 59, 53, 624, DateTimeKind.Unspecified).AddTicks(8550),
                            Descricao = "descricao29a120c8-b821-4ca2-94bc-191510d19b76",
                            FotoUrl = "fotoUrl67e217b3-27cb-4e5b-8b2c-61e7e2fde96f",
                            Marca = "marcadcd0b8a2-5740-4ebe-96ab-459e6db9e1a1",
                            Modelo = "modelo07049e61-8e1e-44be-9b6a-0ae6e8afe5ff",
                            NomeAbreviado = "nomeAbreviado3d8f4b51-1fd8-4e18-8414-5db8afe3af71"
                        },
                        new
                        {
                            Id = 17,
                            DataCompra = new DateTime(2022, 9, 26, 15, 3, 51, 286, DateTimeKind.Unspecified).AddTicks(916),
                            Descricao = "descricao4202b9ce-863a-4d8c-a991-959ca51bd3e8",
                            FotoUrl = "fotoUrl3dd177e4-4118-4fd1-b65e-13a62c928305",
                            Marca = "marca1cb3c9ed-2d3f-427d-a693-da9d27449cc6",
                            Modelo = "modelo35b5cdbe-ffb2-4b8e-8446-a241b048630e",
                            NomeAbreviado = "nomeAbreviado1eefac3b-fccd-4bdf-9049-15c74895c903"
                        },
                        new
                        {
                            Id = 18,
                            DataCompra = new DateTime(2022, 6, 8, 21, 54, 56, 344, DateTimeKind.Unspecified).AddTicks(3438),
                            Descricao = "descricaof8f9bb3a-4ed2-4cff-8682-83960f6e8a8c",
                            FotoUrl = "fotoUrl00d7a7d4-0f3c-4360-a907-1f42b85ee7ee",
                            Marca = "marca7e10e696-df20-4e88-8f27-cafec0be7251",
                            Modelo = "modelo54659d7e-1189-4bca-aad1-b4205f91be3b",
                            NomeAbreviado = "nomeAbreviadob2748b67-482c-4586-b6a8-8b0a2d61bc2e"
                        },
                        new
                        {
                            Id = 19,
                            DataCompra = new DateTime(2021, 8, 24, 20, 4, 5, 606, DateTimeKind.Unspecified).AddTicks(1989),
                            Descricao = "descricao95ff6ec8-4aca-4d18-8b13-3ecdc08d1611",
                            FotoUrl = "fotoUrlfa90338b-83ca-42ef-8d08-e8a3e8754460",
                            Marca = "marca02367fa2-74c6-428b-920f-eb937ef6e6d8",
                            Modelo = "modelo4db50c64-608d-4bbf-b9b8-a603126ff69e",
                            NomeAbreviado = "nomeAbreviadob486359e-508d-4778-9d8c-fcff618b7ab0"
                        },
                        new
                        {
                            Id = 20,
                            DataCompra = new DateTime(2022, 5, 6, 6, 55, 13, 551, DateTimeKind.Unspecified).AddTicks(7726),
                            Descricao = "descricaoc876f97a-a255-45a7-817d-6ae8fe3bb4e6",
                            FotoUrl = "fotoUrl9dc31a52-b941-4671-a919-60c3cd241363",
                            Marca = "marca0a2d40a0-3148-456b-ab09-d9c6e1b91663",
                            Modelo = "modelo23bbb4bc-aca8-4be3-b520-20ff69cb6d41",
                            NomeAbreviado = "nomeAbreviadobb152567-275a-436d-ba4a-0099f1fdd269"
                        },
                        new
                        {
                            Id = 21,
                            DataCompra = new DateTime(2021, 3, 6, 1, 46, 25, 464, DateTimeKind.Unspecified).AddTicks(4579),
                            Descricao = "descricao580c54f4-9e50-4b0d-bf59-1368cffb0d88",
                            FotoUrl = "fotoUrl8c2ed796-cf7f-4743-8da8-5887b89e465c",
                            Marca = "marca6d621e49-131e-4a0f-a1f6-a7faafec793c",
                            Modelo = "modelo36b4f3e6-f89f-4198-ac63-25e3f94a5eef",
                            NomeAbreviado = "nomeAbreviadod68c2f53-2e21-450d-8160-e76f949b454b"
                        },
                        new
                        {
                            Id = 22,
                            DataCompra = new DateTime(2021, 4, 7, 1, 38, 41, 626, DateTimeKind.Unspecified).AddTicks(2518),
                            Descricao = "descricaoa8f8a58a-a180-4419-b927-d22f419e8a67",
                            FotoUrl = "fotoUrl203a39d9-ca08-4d06-bd32-8bd746d5425b",
                            Marca = "marca4cde5cb2-62b6-444f-aff0-49f1757a9643",
                            Modelo = "modelob661b4b6-9f62-4ad3-8069-6d68137a4d81",
                            NomeAbreviado = "nomeAbreviado4925dd2a-e975-452f-bbfe-8555e072e169"
                        },
                        new
                        {
                            Id = 23,
                            DataCompra = new DateTime(2021, 6, 12, 13, 32, 7, 517, DateTimeKind.Unspecified).AddTicks(4185),
                            Descricao = "descricaofbd58577-7539-43bc-a134-d55283432834",
                            FotoUrl = "fotoUrl5d7e06d7-3104-494c-a946-368ed439ff0a",
                            Marca = "marcaf2730703-436a-426c-a7b7-d4afee3639de",
                            Modelo = "modelo415e9c5e-b0a9-4f0d-b1d5-9f0e5690d74d",
                            NomeAbreviado = "nomeAbreviado3dec29bd-d894-458b-8344-8f43ece31125"
                        },
                        new
                        {
                            Id = 24,
                            DataCompra = new DateTime(2020, 6, 17, 3, 52, 18, 648, DateTimeKind.Unspecified).AddTicks(3582),
                            Descricao = "descricao3366d2cd-b131-46cf-b691-a492643261c4",
                            FotoUrl = "fotoUrl7b93515e-6960-48f9-a660-ff26bbb130ee",
                            Marca = "marca9c4c221a-7dec-45cc-8cb8-2d1c6027801e",
                            Modelo = "modelo3a391bd6-1d0b-4acf-9e29-9d93491029a7",
                            NomeAbreviado = "nomeAbreviado6a47226d-e1f1-4a06-a08b-d1eac19feb81"
                        },
                        new
                        {
                            Id = 25,
                            DataCompra = new DateTime(2022, 8, 4, 6, 45, 19, 953, DateTimeKind.Unspecified).AddTicks(6199),
                            Descricao = "descricaod64d6be1-9ddc-47ce-a9b8-f701c8711850",
                            FotoUrl = "fotoUrl0c515397-9323-4519-8662-844eac7e880a",
                            Marca = "marca9b33919d-5fe4-4c2b-8f32-da6d25233dbb",
                            Modelo = "modelodd48df8f-21c1-4e55-881a-c774359728e5",
                            NomeAbreviado = "nomeAbreviado6ef069d3-41a8-4738-a696-507b314a144c"
                        },
                        new
                        {
                            Id = 26,
                            DataCompra = new DateTime(2020, 8, 26, 0, 32, 12, 363, DateTimeKind.Unspecified).AddTicks(838),
                            Descricao = "descricaof0604775-18bb-4927-b586-29d8b4bcb2ea",
                            FotoUrl = "fotoUrl5473be41-b14b-46dd-8549-a15d41a83726",
                            Marca = "marca2c1400c9-c666-4f39-aa1a-6fc2aaac4483",
                            Modelo = "modelo0d7d1c91-fef7-4919-b8ff-ab6719b036e4",
                            NomeAbreviado = "nomeAbreviadoff98dca5-87b3-45bb-93ce-4d2e297ad6d5"
                        },
                        new
                        {
                            Id = 27,
                            DataCompra = new DateTime(2019, 4, 7, 12, 9, 1, 458, DateTimeKind.Unspecified).AddTicks(9444),
                            Descricao = "descricao056fe268-cb78-4b39-87d4-739592245a5b",
                            FotoUrl = "fotoUrl2644e2db-cbf4-4a66-9521-05ec91223130",
                            Marca = "marca3ad1ac5d-57bd-440c-8555-4b5884cc414d",
                            Modelo = "modeloafe9cae3-7ed3-47a0-a2a5-dfd7659e0238",
                            NomeAbreviado = "nomeAbreviado2a5cf548-8d34-40be-becd-bb3c4a47c44f"
                        },
                        new
                        {
                            Id = 28,
                            DataCompra = new DateTime(2019, 11, 27, 17, 9, 38, 477, DateTimeKind.Unspecified).AddTicks(5703),
                            Descricao = "descricaoc3dc0025-8ba3-4306-9feb-508bec30310f",
                            FotoUrl = "fotoUrlb71aa2f7-171c-4ad4-ada6-f60eba320d7c",
                            Marca = "marca31f3d91f-3462-4706-8f2d-8e5d0abde8d2",
                            Modelo = "modelo709d3087-c247-46f7-be14-f3a9c419e15f",
                            NomeAbreviado = "nomeAbreviadoe8ae491d-8bc7-4330-80ea-b8689e3fcc6a"
                        },
                        new
                        {
                            Id = 29,
                            DataCompra = new DateTime(2021, 4, 15, 17, 49, 32, 395, DateTimeKind.Unspecified).AddTicks(2192),
                            Descricao = "descricaoa8028663-e90c-45ff-b526-86c6768cb81c",
                            FotoUrl = "fotoUrlf532715f-69c5-4129-9135-5f8d0c056399",
                            Marca = "marca4ede77c8-4d61-4174-af4d-c1863340ce63",
                            Modelo = "modeloa5ec3a5c-e448-4b52-94b9-59431d60d914",
                            NomeAbreviado = "nomeAbreviado1d6d2179-b8df-420b-a992-98114fb349dc"
                        },
                        new
                        {
                            Id = 30,
                            DataCompra = new DateTime(2020, 6, 17, 14, 36, 29, 109, DateTimeKind.Unspecified).AddTicks(3073),
                            Descricao = "descricaobb99fbd5-da64-47ad-b8ab-a2d3e549727b",
                            FotoUrl = "fotoUrl8390398f-3374-4cac-aa00-5e2973af3d3b",
                            Marca = "marca0c4a0c66-f17e-4fc9-9c00-4fdff3402efd",
                            Modelo = "modelof5ce0a27-01cd-4feb-be3d-95ec78796a49",
                            NomeAbreviado = "nomeAbreviadocb3577fc-fc52-47cf-8f93-76b89aef70e2"
                        },
                        new
                        {
                            Id = 31,
                            DataCompra = new DateTime(2022, 1, 14, 18, 18, 56, 286, DateTimeKind.Unspecified).AddTicks(4692),
                            Descricao = "descricaoa9e439f6-83a2-4e44-8d4a-56176653b558",
                            FotoUrl = "fotoUrl8f1ffe33-b101-4e6f-90d2-ced4b7c325fd",
                            Marca = "marca52a13a0d-23b9-4595-991e-d54ab919b70a",
                            Modelo = "modeloe07de6d0-bbad-494a-9d60-727ab3669e74",
                            NomeAbreviado = "nomeAbreviado256185b4-01c8-485b-bab4-540eb4cb8763"
                        },
                        new
                        {
                            Id = 32,
                            DataCompra = new DateTime(2021, 9, 11, 13, 9, 21, 759, DateTimeKind.Unspecified).AddTicks(4004),
                            Descricao = "descricao1471ccfb-0a65-4112-b39e-fc1327a4e13c",
                            FotoUrl = "fotoUrl52d29c69-9c77-4ee2-90bf-243b01f4178d",
                            Marca = "marca1f56937a-c14f-4365-929f-7d7af5dc3afa",
                            Modelo = "modelo2140c733-88d9-45fc-bc3b-99311b6372b3",
                            NomeAbreviado = "nomeAbreviadod01475b0-03d2-4b2c-a8ac-46c70ede120d"
                        },
                        new
                        {
                            Id = 33,
                            DataCompra = new DateTime(2021, 3, 23, 3, 31, 9, 213, DateTimeKind.Unspecified).AddTicks(1921),
                            Descricao = "descricaoa147e555-2865-403e-9ecd-ce68b899c3f6",
                            FotoUrl = "fotoUrlca97f48d-e631-4539-a8cd-1bb1366cfe1a",
                            Marca = "marca66d44310-a859-42b1-b8c1-b3f293594e24",
                            Modelo = "modelo13c45647-be00-40ea-a9b1-0a68eca9bbae",
                            NomeAbreviado = "nomeAbreviadocb743668-66d1-4c70-bb3a-8ee6c0060d00"
                        },
                        new
                        {
                            Id = 34,
                            DataCompra = new DateTime(2022, 4, 17, 19, 43, 43, 122, DateTimeKind.Unspecified).AddTicks(9570),
                            Descricao = "descricao631a9b92-0b81-4f68-bd7b-a37b301ded20",
                            FotoUrl = "fotoUrl5775f76d-fa8d-470a-bbc7-e84af09d5d44",
                            Marca = "marca095ff863-64f8-4383-a27a-e059e6414b6d",
                            Modelo = "modeloec6821ed-52e9-4c50-9116-1e0156980fd1",
                            NomeAbreviado = "nomeAbreviado18b559a7-dc04-4746-bf09-9c272bc40c49"
                        },
                        new
                        {
                            Id = 35,
                            DataCompra = new DateTime(2021, 10, 24, 3, 49, 14, 437, DateTimeKind.Unspecified).AddTicks(3811),
                            Descricao = "descricaod7b33593-5fe2-40bf-8a7a-353fdb516eb5",
                            FotoUrl = "fotoUrld5241bd5-4bca-4fb6-8602-a9e93157c58b",
                            Marca = "marca105d0371-b099-4901-8ef1-bacef1d61484",
                            Modelo = "modelo22efb9df-81f0-472a-97c9-106075d981d5",
                            NomeAbreviado = "nomeAbreviadoc20f2c60-7141-4cbc-a002-9aaf85ab28da"
                        },
                        new
                        {
                            Id = 36,
                            DataCompra = new DateTime(2020, 9, 10, 8, 7, 21, 626, DateTimeKind.Unspecified).AddTicks(4067),
                            Descricao = "descricaofb29b629-b1b4-4f64-8ef7-942eefe8d256",
                            FotoUrl = "fotoUrlc1a61f31-70ca-4d31-98b1-0160b69905a9",
                            Marca = "marca4e3cae73-81ba-4037-a226-eb3a8989a46a",
                            Modelo = "modelof037c94e-9167-434b-a31d-8ad88fbb9a43",
                            NomeAbreviado = "nomeAbreviado6f0e0915-1f41-46e4-adea-f85c892e3f87"
                        },
                        new
                        {
                            Id = 37,
                            DataCompra = new DateTime(2021, 9, 19, 4, 15, 54, 612, DateTimeKind.Unspecified).AddTicks(3510),
                            Descricao = "descricao77b46eee-3020-40ce-95ac-5c12c304a934",
                            FotoUrl = "fotoUrl6ebefc97-bc33-4b2b-a1ea-7512c4b0fd46",
                            Marca = "marcadfbb08f4-992a-4544-b515-c2236215c862",
                            Modelo = "modelod445d111-3eb3-4737-9227-9bb19b9e28bf",
                            NomeAbreviado = "nomeAbreviado4718083a-5309-4e62-b09c-311c1a8a72bf"
                        },
                        new
                        {
                            Id = 38,
                            DataCompra = new DateTime(2020, 4, 20, 18, 13, 3, 851, DateTimeKind.Unspecified).AddTicks(1515),
                            Descricao = "descricao25da862a-a155-458b-877e-262001ae3898",
                            FotoUrl = "fotoUrl786a915e-957b-4f70-9c2d-ded57c9c5d1e",
                            Marca = "marca7b548820-3c38-47bb-a54c-7c5da06a1b83",
                            Modelo = "modelo04054e8c-0e63-4bcb-a5cb-5244675c8192",
                            NomeAbreviado = "nomeAbreviado7c73b874-1756-45e1-9681-31d9719600d6"
                        },
                        new
                        {
                            Id = 39,
                            DataCompra = new DateTime(2019, 9, 9, 9, 49, 55, 329, DateTimeKind.Unspecified).AddTicks(368),
                            Descricao = "descricao61010c54-b5d4-464e-a799-09cd829d3c71",
                            FotoUrl = "fotoUrla23fc042-6c72-4cef-884e-420c2544c2fd",
                            Marca = "marca52ff4023-7b76-4f5b-8bb3-df9b1a03933f",
                            Modelo = "modelof75ff9f7-072d-4685-a6e9-53467a56ef40",
                            NomeAbreviado = "nomeAbreviadoed2d65e4-4e7f-440e-b8c3-e0db271ae247"
                        },
                        new
                        {
                            Id = 40,
                            DataCompra = new DateTime(2022, 9, 21, 5, 58, 10, 502, DateTimeKind.Unspecified).AddTicks(2223),
                            Descricao = "descricao5c27347a-7b5e-4a38-beb7-1aa87f5ee75e",
                            FotoUrl = "fotoUrl17dcc49a-2960-4901-aef4-0b17b426d6b2",
                            Marca = "marca4ce35ee8-1ef5-49f2-8583-e303afbb3528",
                            Modelo = "modelo57500f60-6dcc-4e0e-8142-12fe09e9bf49",
                            NomeAbreviado = "nomeAbreviado6b1a0087-e439-4cfc-811b-62a0c7a54d86"
                        },
                        new
                        {
                            Id = 41,
                            DataCompra = new DateTime(2022, 11, 1, 20, 58, 25, 89, DateTimeKind.Unspecified).AddTicks(6284),
                            Descricao = "descricao99e0b542-929e-45d8-b92a-97d3fab06ac6",
                            FotoUrl = "fotoUrl0c86d4c3-61e5-440d-92fc-5675020d6b9f",
                            Marca = "marcabb1e55eb-9f12-436d-93dd-f4496acc9403",
                            Modelo = "modeloa55b5614-ddc8-4a68-8dc6-6b8286fa90d6",
                            NomeAbreviado = "nomeAbreviadoc34eaa68-e413-4ef1-8514-5c088c12544b"
                        },
                        new
                        {
                            Id = 42,
                            DataCompra = new DateTime(2020, 9, 19, 21, 0, 56, 363, DateTimeKind.Unspecified).AddTicks(2476),
                            Descricao = "descricao01b3d5ba-7d42-4c5d-9f21-8ebcaa1ab701",
                            FotoUrl = "fotoUrld8644aa0-0236-459a-aa6d-c3b892f93b42",
                            Marca = "marca701ef682-b342-4d28-82e1-9e4e57520f41",
                            Modelo = "modeloa5054ac6-d87e-48b0-9dad-06603f28a33f",
                            NomeAbreviado = "nomeAbreviado720bcf11-98dd-4e22-9e60-306ee8e9bedc"
                        },
                        new
                        {
                            Id = 43,
                            DataCompra = new DateTime(2022, 3, 27, 10, 24, 6, 191, DateTimeKind.Unspecified).AddTicks(6319),
                            Descricao = "descricao8b7166f1-c731-4d8e-af73-2491942b97c3",
                            FotoUrl = "fotoUrl667d9c17-fcb3-468e-895f-23e7aa2dbeed",
                            Marca = "marcad2ce0f3e-63f5-41a7-8b65-a49d9cb53990",
                            Modelo = "modelo5e9fef4b-478e-481f-bde3-110c1fb95898",
                            NomeAbreviado = "nomeAbreviado7e7f4248-5e33-48bb-920a-043207f6f858"
                        },
                        new
                        {
                            Id = 44,
                            DataCompra = new DateTime(2020, 2, 22, 6, 37, 23, 202, DateTimeKind.Unspecified).AddTicks(4356),
                            Descricao = "descricaoa8404d1c-0645-4306-9081-93a709392bc2",
                            FotoUrl = "fotoUrlec6b7026-c51e-41f3-a6e5-36f1e42d3a09",
                            Marca = "marcae7eb8167-268e-49cc-9e6d-aaaa8022b2cd",
                            Modelo = "modelo120d6f4e-b36f-43fb-aac7-d237bbd5cf49",
                            NomeAbreviado = "nomeAbreviadoa689d6e7-4ba6-47d9-86ce-3e2932c6369c"
                        },
                        new
                        {
                            Id = 45,
                            DataCompra = new DateTime(2019, 2, 11, 14, 39, 56, 264, DateTimeKind.Unspecified).AddTicks(2546),
                            Descricao = "descricao58bc97a1-c97d-438b-9fac-bb5a6a8a1fdb",
                            FotoUrl = "fotoUrl07287343-e03e-4a71-9f6a-cdb66efb6db7",
                            Marca = "marca1dac986d-972b-4c1f-a76a-d3f5d5699983",
                            Modelo = "modeloabf08a0c-42f8-4a3c-a4b1-7c64e3dddc28",
                            NomeAbreviado = "nomeAbreviado7a620fd0-bdf9-49f0-bec5-7a0288a229dc"
                        },
                        new
                        {
                            Id = 46,
                            DataCompra = new DateTime(2020, 2, 15, 23, 56, 35, 138, DateTimeKind.Unspecified).AddTicks(6282),
                            Descricao = "descricaob019572e-30e6-48b1-ac89-7afe34cad888",
                            FotoUrl = "fotoUrl964b93ea-2eff-4acf-8d7e-ced273fbaa71",
                            Marca = "marca47748a5d-4542-4b85-a2bc-f818143bca0d",
                            Modelo = "modelo80c88ca6-8b2e-44f7-879f-0616c065d828",
                            NomeAbreviado = "nomeAbreviado8c5d8710-adaa-4c23-bead-984fd5218dd5"
                        },
                        new
                        {
                            Id = 47,
                            DataCompra = new DateTime(2021, 6, 16, 1, 31, 5, 658, DateTimeKind.Unspecified).AddTicks(8154),
                            Descricao = "descricaofaa88083-8fa5-44e2-8004-b44d040b3eca",
                            FotoUrl = "fotoUrlecf24cf5-586b-40e3-adbe-bb6806330f70",
                            Marca = "marcacb132f1d-de44-498f-b247-5b15201d3a4a",
                            Modelo = "modelodfbaab32-08fa-4916-8fb0-32df888b35fb",
                            NomeAbreviado = "nomeAbreviado8dccc91f-521e-4c9c-884e-ee06a31b8dec"
                        },
                        new
                        {
                            Id = 48,
                            DataCompra = new DateTime(2020, 1, 4, 13, 19, 59, 393, DateTimeKind.Unspecified).AddTicks(7162),
                            Descricao = "descricaoea18b3d7-39c4-424c-8d82-bd96a97459ef",
                            FotoUrl = "fotoUrl82d6d051-c38b-47fa-9eed-d8a50f5517ad",
                            Marca = "marca48f71622-4023-4fd0-bca9-00ff2e07e2c8",
                            Modelo = "modelof57b433b-fa90-4b0f-a46d-6430ba573e95",
                            NomeAbreviado = "nomeAbreviado832ab978-d80d-4556-a28e-33819341e989"
                        },
                        new
                        {
                            Id = 49,
                            DataCompra = new DateTime(2020, 11, 30, 10, 47, 36, 917, DateTimeKind.Unspecified).AddTicks(7250),
                            Descricao = "descricao6c1e77de-6842-4d3b-86fd-034ba1428710",
                            FotoUrl = "fotoUrl236eec24-0b2d-462e-bf54-ce081948b4cb",
                            Marca = "marcae466e244-7bcd-468c-aea9-edfbb84b8f22",
                            Modelo = "modelo11015f7f-7fc9-48fb-aab0-e48f757a9a9b",
                            NomeAbreviado = "nomeAbreviado0b962281-a18d-469d-b050-40f58601ce91"
                        },
                        new
                        {
                            Id = 50,
                            DataCompra = new DateTime(2019, 5, 24, 3, 22, 21, 622, DateTimeKind.Unspecified).AddTicks(7221),
                            Descricao = "descricao7b7c693c-f60a-427c-840e-d8c7d7dc77a9",
                            FotoUrl = "fotoUrlc43f212b-bd2a-4351-85c5-84d2ee129ab4",
                            Marca = "marca25a30ad1-9e35-46a4-a423-1cbe13d26b8b",
                            Modelo = "modelo2b8d5096-5ae5-4b05-ac44-81f6c9017c2a",
                            NomeAbreviado = "nomeAbreviadocc06a3fb-e429-4094-a3a0-45b22a6c6934"
                        });
                });

            modelBuilder.Entity("Almocherifado.core.AgregateRoots.FerramentaNm.FerramentaEmprestada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataDevolucao")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EmprestimoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FerramentaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmprestimoId");

                    b.HasIndex("FerramentaId");

                    b.HasIndex("Id");

                    b.ToTable("FerramentaEmprestada");
                });

            modelBuilder.Entity("Almocherifado.core.AgregateRoots.FuncionarioNm.Funcionario", b =>
                {
                    b.Property<string>("CPF")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("CPF");

                    b.ToTable("Funcionarios");

                    b.HasData(
                        new
                        {
                            CPF = "22904652833",
                            Email = "Dorothy.Nogueira@live.com",
                            Nome = "Frances Nogueira"
                        },
                        new
                        {
                            CPF = "07462732076",
                            Email = "Ruby_Silva46@bol.com.br",
                            Nome = "Robyn Nogueira"
                        },
                        new
                        {
                            CPF = "15639858532",
                            Email = "Bridget_Franco26@gmail.com",
                            Nome = "Kathy Braga"
                        },
                        new
                        {
                            CPF = "61201392578",
                            Email = "Eugene_Moreira@gmail.com",
                            Nome = "Joanne Silva"
                        },
                        new
                        {
                            CPF = "27470782648",
                            Email = "Alonzo_Pereira60@live.com",
                            Nome = "Marty Moraes"
                        },
                        new
                        {
                            CPF = "19491090461",
                            Email = "Henrietta.Carvalho70@gmail.com",
                            Nome = "Joshua Braga"
                        },
                        new
                        {
                            CPF = "44119773540",
                            Email = "Bryan79@hotmail.com",
                            Nome = "Emanuel Batista"
                        },
                        new
                        {
                            CPF = "97441563682",
                            Email = "Deborah.Barros59@yahoo.com",
                            Nome = "Drew Carvalho"
                        },
                        new
                        {
                            CPF = "83721484819",
                            Email = "Floyd_Costa28@hotmail.com",
                            Nome = "Tammy Martins"
                        },
                        new
                        {
                            CPF = "48670820668",
                            Email = "Isaac_Carvalho73@bol.com.br",
                            Nome = "Darrel Albuquerque"
                        });
                });

            modelBuilder.Entity("Almocherifado.core.AgregateRoots.EmprestimoNm.Emprestimo", b =>
                {
                    b.HasOne("Almocherifado.core.AgregateRoots.FuncionarioNm.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioCPF")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("Almocherifado.core.AgregateRoots.FerramentaNm.FerramentaEmprestada", b =>
                {
                    b.HasOne("Almocherifado.core.AgregateRoots.EmprestimoNm.Emprestimo", "Emprestimo")
                        .WithMany("FerramentasEmprestas")
                        .HasForeignKey("EmprestimoId");

                    b.HasOne("Almocherifado.core.AgregateRoots.FerramentaNm.Ferramenta", "Ferramenta")
                        .WithMany("HistoricoEmprestimos")
                        .HasForeignKey("FerramentaId");

                    b.Navigation("Emprestimo");

                    b.Navigation("Ferramenta");
                });

            modelBuilder.Entity("Almocherifado.core.AgregateRoots.EmprestimoNm.Emprestimo", b =>
                {
                    b.Navigation("FerramentasEmprestas");
                });

            modelBuilder.Entity("Almocherifado.core.AgregateRoots.FerramentaNm.Ferramenta", b =>
                {
                    b.Navigation("HistoricoEmprestimos");
                });
#pragma warning restore 612, 618
        }
    }
}
