// <auto-generated />
using System;
using Almocherifado.InfraEstrutura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Almocherifado.InfraEstrutura.Migrations
{
    [DbContext(typeof(AlmocherifadoContext))]
    partial class AlmocherifadoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Almocherifado.core.AgregateRoots.EmprestimoNm.Emprestimo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Entrega")
                        .HasColumnType("datetime2");

                    b.Property<string>("FuncionariocpfStr")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Obra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TermoResponsabilidade")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FuncionariocpfStr");

                    b.ToTable("Emprestimos");
                });

            modelBuilder.Entity("Almocherifado.core.AgregateRoots.FerramentaNm.Ferramenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataCompra")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeAbreviado")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ferramentas");
                });

            modelBuilder.Entity("Almocherifado.core.AgregateRoots.FerramentaNm.FerramentaEmprestada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DataDevolucao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EmprestimoId")
                        .HasColumnType("int");

                    b.Property<int?>("FerramentaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmprestimoId");

                    b.HasIndex("FerramentaId");

                    b.HasIndex("Id");

                    b.ToTable("FerramentaEmprestada");
                });

            modelBuilder.Entity("Almocherifado.core.AgregateRoots.FuncionarioNm.Funcionario", b =>
                {
                    b.Property<string>("cpfStr")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CPF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("cpfStr");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("Almocherifado.core.AgregateRoots.EmprestimoNm.Emprestimo", b =>
                {
                    b.HasOne("Almocherifado.core.AgregateRoots.FuncionarioNm.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionariocpfStr")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("Almocherifado.core.AgregateRoots.FerramentaNm.FerramentaEmprestada", b =>
                {
                    b.HasOne("Almocherifado.core.AgregateRoots.EmprestimoNm.Emprestimo", "Emprestimo")
                        .WithMany("FerramentasEmprestas")
                        .HasForeignKey("EmprestimoId");

                    b.HasOne("Almocherifado.core.AgregateRoots.FerramentaNm.Ferramenta", "Ferramenta")
                        .WithMany("HistoricoEmprestimos")
                        .HasForeignKey("FerramentaId");

                    b.Navigation("Emprestimo");

                    b.Navigation("Ferramenta");
                });

            modelBuilder.Entity("Almocherifado.core.AgregateRoots.EmprestimoNm.Emprestimo", b =>
                {
                    b.Navigation("FerramentasEmprestas");
                });

            modelBuilder.Entity("Almocherifado.core.AgregateRoots.FerramentaNm.Ferramenta", b =>
                {
                    b.Navigation("HistoricoEmprestimos");
                });
#pragma warning restore 612, 618
        }
    }
}
